#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# and setting up a custom 404 error page.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y
sudo apt-get install -y ufw

echo -e "\nSetting up some minor stuff.\n"

# Enable firewall and allow Nginx HTTP
sudo ufw enable
sudo ufw allow 'Nginx HTTP'

# Starting nginx service
sudo service nginx start

# Backup default nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bckp

# Create custom 404 error page
echo -e "Ceci n'est pas une page" > /var/www/html/404.html

# Adding the custom 404 page configuration to Nginx
echo -e "\nConfiguring custom 404 page...\n"
sudo sed -i "/server_name bonaeineza31.tech;/a \\
    error_page 404 /404.html; \n\
    location = /404.html { \n\
        root /var/www/html; \n\
        internal; \n\
    }" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nCustom 404 page setup completed.\n"

